CarRepairs/CarRepairs/Controllers/HomeController.cs
using AutoMapper;
using CarRepairs.DAL.Models;
using CarRepairs.UI.Models;
using CarRepairs.SL;
using CarRepairs.UI.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarRepairs.UI.Controllers
{
    public class HomeController : Controller
    {
        readonly IVehicleService _vehicleService;
        readonly IImageService _imageService;
        public HomeController(IVehicleService vehicleService, IImageService imageService)
        {
            _vehicleService = vehicleService;
            _imageService = imageService;
        }

        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                var dataVehicles = _vehicleService.GetVehicles(User.Identity.GetUserId()).ToList();
                List<VehicleModel> vehicles = new List<VehicleModel>();
                Mapper.Map(dataVehicles, vehicles);

                var dataImages = _imageService.GetImages(User.Identity.GetUserId()).ToList();
                List<ImageModel> images = new List<ImageModel>();
                Mapper.Map(dataImages, images);

                var viewModel = new UserVehiclesImagesViewModel();
                foreach (var v in vehicles)
                {
                    viewModel.VehicleImageModels.Add(new VehicleImageViewModel
                    {
                        Vehicle = v,
                        Image = images.FirstOrDefault(i => i.Id == v.Id) ?? new ImageModel(),
                    });
                }
                    
                return View(viewModel);
            }
            else
                return View();
        }

    }
}

CarRepairs/CarRepairs/Controllers/RepairController.cs
using AutoMapper;
using CarRepairs.UI.Models;
using CarRepairs.SL;
using CarRepairs.DAL.Models;
using CarRepairs.UI.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CarRepairs.UI.Controllers
{
    [Authorize]
    public class RepairController : Controller
    {
        readonly IRepairService _repairService;
        readonly IVehicleService _vehicleService;
        readonly IRepairPartService _repairPartService;
        public RepairController(IRepairService repairService, IVehicleService vehicleService, IRepairPartService repairPartService)
        {
            _repairService = repairService;
            _vehicleService = vehicleService;
            _repairPartService = repairPartService;
        }

        public ViewResult DisplayList()
        {
            var dataRepair = _repairService.GetRepairsByUser(User.Identity.GetUserId()).ToList();
            List<RepairModel> repairModels = new List<RepairModel>();
            Mapper.Map(dataRepair, repairModels);

            var viewModel = new UserRepairsViewModel
            {
                Repairs = repairModels
            };
            return View(viewModel);
        }

        public ActionResult Create(int? vehicleId)
        {
            if (vehicleId == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var dataVehicle = _vehicleService.GetVehicle((int)vehicleId, User.Identity.GetUserId());
            if(dataVehicle == null)
                return HttpNotFound();

            RepairModel repairModel = new RepairModel
            {
                VehicleId = dataVehicle.Id,
                Date = DateTime.Today
            };

            VehicleRepairViewModel vehicleRepairViewModel = new VehicleRepairViewModel
            {
                VehicleName = dataVehicle.Producent + " " + dataVehicle.ModelName,
                Repair = repairModel,
            };

            return View(vehicleRepairViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VehicleRepairViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Repair repair = new Repair();
                    Mapper.Map(model.Repair, repair);
                    _repairService.CreateRepair(repair, User.Identity.GetUserId());
                    return RedirectToAction("Create", "RepairPart", new {repairID = repair.Id });
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Nie udało się zapisać zmian. Spróbuj ponownie później, jeżeli problem nie ustępuje skontaktuj się z administratorem.");
            }

            return View(model);
        }

        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (saveChangesError.GetValueOrDefault())
                ViewBag.ErrorMessage = "Nie udało się usunąć danych. Spróbuj ponownie później, jeżeli problem nie ustępuje skontaktuj się z administratorem.";

            var dataRepair = _repairService.GetRepair((int)id, User.Identity.GetUserId());
            if (dataRepair == null)
                return HttpNotFound();
            
            RepairModel repairModel = new RepairModel();
            Mapper.Map(dataRepair, repairModel);
            VehicleRepairViewModel vehicleRepairViewModel = new VehicleRepairViewModel
            {
                VehicleName = dataRepair.Vehicle.Producent + " " + dataRepair.Vehicle.ModelName,
                Repair = repairModel,
            };

            return View(vehicleRepairViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var dataRepair = _repairService.GetRepair(id, User.Identity.GetUserId());
                _repairService.RemoveRepair(dataRepair, User.Identity.GetUserId());
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new { id, saveChangesError = true });
            }
            return RedirectToAction("DisplayList");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var dataRepair = _repairService.GetRepair((int)id, User.Identity.GetUserId());
            if (dataRepair == null)
                return HttpNotFound();

            RepairModel repairModel = new RepairModel();
            Mapper.Map(dataRepair, repairModel);

            var repairParts = _repairPartService.GetRepairParts(dataRepair.Id).ToList();
            List<RepairPartModel> repairPartModels = new List<RepairPartModel>();
            Mapper.Map(repairParts, repairPartModels);

            VehicleRepairViewModel vehicleRepairViewModel = new VehicleRepairViewModel
            {
                VehicleName = dataRepair.Vehicle.Producent + " " + dataRepair.Vehicle.ModelName,
                Repair = repairModel,
                RepairParts = repairPartModels,
            };

            return View(vehicleRepairViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VehicleRepairViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Repair repair = new Repair();
                    Mapper.Map(model.Repair, repair);
                    _repairService.UpdateRepair(repair, User.Identity.GetUserId());
                    return RedirectToAction("DisplayList");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Nie udało się zapisać zmian. Spróbuj ponownie, jeżeli problem nie ustępuje skontaktuj się z administratorem.");
            }
            return View(model);
        }
    }
}

CarRepairs/CarRepairs/Controllers/VehicleController.cs
using AutoMapper;
using CarRepairs.DAL.Models;
using CarRepairs.UI.Models;
using CarRepairs.SL;
using CarRepairs.UI.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CarRepairs.UI.Controllers
{
    [Authorize]
    public class VehicleController : Controller
    {
        readonly IVehicleService _vehicleService;
        readonly IImageService _imageService;
        public VehicleController(IVehicleService vehicleService, IImageService imageService)
        {
            _vehicleService = vehicleService;
            _imageService = imageService;
        }

        public ViewResult DisplayList()
        {
            var dataVehicles = _vehicleService.GetVehicles(User.Identity.GetUserId()).ToList();

            List<VehicleModel> vehicles = new List<VehicleModel>();
            Mapper.Map(dataVehicles, vehicles);

            var viewModel = new UserVehiclesViewModel
            {
                Vehicles = vehicles,
            };
            return View(viewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VehicleModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Vehicle dataModel = new Vehicle();
                    Mapper.Map(model, dataModel);
                    _vehicleService.Create(dataModel, User.Identity.GetUserId());
                    return RedirectToAction("DisplayList");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Nie udało się zapisać zmian. Spróbuj ponownie, jeżeli problem nie ustępuje skontaktuj się z administratorem.");
            }

            return View();
        }

        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (saveChangesError.GetValueOrDefault())
                ViewBag.ErrorMessage = "Nie udało się odczytać danych. Spróbuj ponownie, jeżeli problem nie ustępuje skontaktuj się z administratorem.";

            var dataVehicle = _vehicleService.GetVehicle((int)id, User.Identity.GetUserId());
            if (dataVehicle == null)
                return HttpNotFound();

            VehicleModel vehicle = new VehicleModel();
            Mapper.Map(dataVehicle, vehicle);
            return View(vehicle);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var dataVehicle = _vehicleService.GetVehicle(id, User.Identity.GetUserId());
                _vehicleService.Remove(dataVehicle, User.Identity.GetUserId());
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new { id, saveChangesError = true });
            }
            return RedirectToAction("DisplayList");
        }

        public ActionResult Edit(int? id, bool? saveChangesError = false)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (saveChangesError.GetValueOrDefault())
                ViewBag.ErrorMessage = "Nie udało się odczytać danych. Spróbuj ponownie, jeżeli problem nie ustępuje skontaktuj się z administratorem.";

            var dataVehicle = _vehicleService.GetVehicle((int)id, User.Identity.GetUserId());
            if (dataVehicle == null)
                return HttpNotFound();

            VehicleModel vehicle = new VehicleModel();
            Mapper.Map(dataVehicle, vehicle);

            var dataImage = _imageService.GetImage(vehicle.Id, User.Identity.GetUserId());
            ImageModel image = new ImageModel();
            if(dataImage != null)
                Mapper.Map(dataImage, image);

            VehicleImageViewModel vehicleImageView = new VehicleImageViewModel
            {
                Vehicle = vehicle,
                Image = image,
            };
            return View(vehicleImageView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VehicleImageViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Vehicle dataVehicle = new Vehicle();
                    Mapper.Map(model.Vehicle, dataVehicle);
                    _vehicleService.Update(dataVehicle, User.Identity.GetUserId());
                    return RedirectToAction("DisplayList");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Nie udało się zapisać zmian. Spróbuj ponownie, jeżeli problem nie ustępuje skontaktuj się z administratorem.");
            }
            return View(model);
        }
    }
}

CarRepairs/CarRepairs/Views/Home/Index.cshtml
@model CarRepairs.UI.ViewModels.UserVehiclesImagesViewModel
@if (Request.IsAuthenticated)
{
    <div class="container">
        @foreach (var v in Model.VehicleImageModels)
        {
            <h2 class="mt-3 mb-3" style="text-align:center">@v.Vehicle.Producent @v.Vehicle.ModelName</h2>
            <div class="row bg-white">
                    <div class="col-12 col-md-6 better-figure">
                        <figure class="better-figure">
                            <a style="display:block; text-decoration:none;" href="@Url.Action("Edit", "Vehicle", new { id = v.Vehicle.Id })">
                                <img src="@Url.Content(v.Image.Path)" class="rounded photo-size better-img" alt="@v.Image.Title">
                            </a>
                        </figure>
                    </div>
                <div class="col-12 col-md-6">
                    <ul class="better-info">
                        <li><b>Marka</b>: @v.Vehicle.Producent</li>
                        <li>Model: @v.Vehicle.ModelName</li>
                        <li>Rok produkcji: @v.Vehicle.ProductionYear r.</li>
                        <li>Przebieg: @v.Vehicle.Mileage km</li>
                        <li>Pojemność skokowa: @v.Vehicle.EngineCapacity cm<sup>3</sup></li>
                        <li>Moc silnika: @v.Vehicle.EnginePower KM</li>
                        <li>Data zakupu: @v.Vehicle.PurchaseDate.ToShortDateString()</li>
                        <li>Cena zakupu: @v.Vehicle.PurchasePrice zł</li>
                    </ul>
                </div>
                <div class="col-12">
                    <h4 class="text-black-50 my-3"> Naprawy </h4>
                    @Html.ActionLink("Dodaj", "Create", "Repair", new { vehicleId = v.Vehicle.Id }, new { @class = "btn btn-success" })
                    @if (v.Vehicle.Repairs.Count == 0)
                    {
                        <div class="col-12 repair-empty-field bg-secondary rounded">
                            <i>Brak napraw</i>
                        </div>
                    }
                    else
                    {
                        foreach (var r in v.Vehicle.Repairs)
                        {
                            <a style="display:block; text-decoration:none;" href="@Url.Action("Edit", "Repair", new { id = r.Id })">
                                <div class="col-12 repair-field rounded">
                                    @r.Name
                                </div>
                            </a>
                        }
                    }
                </div>
            </div>
            <div class="row bg-light" style="min-height:100px">
                <div class="col-12">

                </div>
            </div>
        }
    </div>
}
else
{
    <div class="jumbotron" style="padding: 2rem;">
        <h1 class="text-center">Dziennik pojazdów</h1>
        <p class="lead">
            Przechowuj informacje o swoich pojazdach, naprawach, kosztach eksploatacyjnych. Zaloguj się aby móc skorzystać z usług,&nbsp;
            a jeżeli jeszcze tego nie zrobiłeś utwórz darmowe konto i spróbuj.
            <br />
        </p>

        <div class="col-xs-1 text-center" style="margin-top:2rem;">
            <ul class="list-inline">
                <li class="list-inline-item">
                    @Html.ActionLink("Zarejestruj", "Register", "Account", routeValues: null, htmlAttributes: new {
                                    id = "registerLink", @class="btn btn-primary btn-lg"})
                </li>
                <li class="list-inline-item">
                    @Html.ActionLink("Zaloguj", "Login", "Account", routeValues: null, htmlAttributes: new {
                                       id = "loginLink", @class = "btn btn-primary btn-lg" })
                </li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Dane techniczne</h2>
            <p>
                Przechowuj potrzebne dane techniczne swoich pojazdów i korzystaj z nich w każdym momencie.
            </p>
        </div>
        <div class="col-md-4">
            <h2>Koszty napraw</h2>
            <p> Zapisuj koszty napraw związanych z pojazdami, ceny części, usługi warsztatów, paragony i faktury.</p>
        </div>
        <div class="col-md-4">
            <h2>Statystyki spalania</h2>
            <p> Zbieraj informacje po każdym tankowaniu, aby otrzymać statystyki dotyczące spalania.</p>
        </div>
    </div>
}